// Subsets the webfonts down to the characters this site actually uses.
//
// Why: fontsource ships fonts split into unicode-range @font-face blocks —
// 124 of them for Noto Sans JP. Two problems follow. All those declarations
// land in the render-blocking stylesheet (~26KB of CSS), and the files that do
// get fetched are full subsets: Inter's latin-ext is 85KB, pulled onto the
// critical path by the two pinyin tone marks in a lesson note.
//
// This keeps only the blocks whose range covers a character we use, and
// re-encodes each retained file down to just those glyphs.
//
// Runs before dev and build. Output is gitignored — it regenerates from
// node_modules, so a fresh clone or a CI build reproduces it exactly.

import { readFile, writeFile, mkdir, readdir, rm } from 'node:fs/promises';
import path from 'node:path';
import subsetFont from 'subset-font';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT_DIR = path.join(ROOT, 'public/fonts');
const CSS_OUT = path.join(ROOT, 'src/styles/fonts.css');

const FONTS = [
  { pkg: '@fontsource-variable/inter', css: 'wght.css', family: 'Inter Variable' },
  { pkg: '@fontsource-variable/noto-sans-jp', css: 'wght.css', family: 'Noto Sans JP Variable' },
];

const SOURCE_DIRS = ['src/content', 'src/pages', 'src/components', 'src/layouts'];

async function* walk(dir) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (/\.(md|astro|ts|json)$/.test(entry.name)) yield full;
  }
}

// Characters found in source, plus a Latin baseline. The baseline matters:
// the search box echoes whatever a visitor types, and content-derived glyphs
// alone would leave ordinary letters missing from an unrelated query.
const used = new Set();
for (let cp = 0x20; cp <= 0x7e; cp += 1) used.add(String.fromCodePoint(cp));
for (const ch of '£€•–—‘’“”…°×÷±≈≠é è ê ë á à â ä ó ò ô ö ú ù û ü í ì î ï ñ ç ' + '「」、。・ー') {
  used.add(ch);
}
for (const dir of SOURCE_DIRS) {
  for await (const file of walk(path.join(ROOT, dir))) {
    for (const ch of await readFile(file, 'utf8')) used.add(ch);
  }
}

const parseRanges = (value) =>
  value.split(',').map((part) => {
    const [from, to] = part.trim().replace(/^U\+/i, '').split('-');
    return [parseInt(from, 16), parseInt(to ?? from, 16)];
  });

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

const emitted = [];
let totalBefore = 0;
let totalAfter = 0;
let blocksSeen = 0;

for (const font of FONTS) {
  const pkgDir = path.join(ROOT, 'node_modules', font.pkg);
  const css = await readFile(path.join(pkgDir, font.css), 'utf8');
  const blocks = css.match(/@font-face\s*{[^}]*}/g) ?? [];
  blocksSeen += blocks.length;

  for (const block of blocks) {
    const rangeText = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    const file = block.match(/url\(\.\/files\/([^)]+)\)/)?.[1];
    if (!rangeText || !file) continue;

    const ranges = parseRanges(rangeText);
    const keep = [...used].filter((ch) => {
      const cp = ch.codePointAt(0);
      return ranges.some(([lo, hi]) => cp >= lo && cp <= hi);
    });
    if (keep.length === 0) continue;

    const source = await readFile(path.join(pkgDir, 'files', file));
    const subset = await subsetFont(source, keep.join(''), { targetFormat: 'woff2' });
    totalBefore += source.length;
    totalAfter += subset.length;

    const outName = file.replace(/\.woff2$/, '.subset.woff2');
    await writeFile(path.join(OUT_DIR, outName), subset);

    emitted.push(
      block
        .replace(/url\(\.\/files\/[^)]+\)/, `url('/fonts/${outName}')`)
        .replace(/format\('[^']*'\)/, "format('woff2')")
        .replace(/font-family:\s*'[^']+'/, `font-family: '${font.family}'`),
    );
  }
}

await writeFile(
  CSS_OUT,
  `/* GENERATED by scripts/subset-fonts.mjs — do not edit by hand.
   ${emitted.length} of ${blocksSeen} @font-face blocks kept, glyph-subset to
   the characters this site uses. Regenerate with: npm run fonts */\n${emitted.join('\n')}\n`,
);

const kb = (n) => `${(n / 1024).toFixed(1)}K`;
console.log(
  `[subset-fonts] ${emitted.length}/${blocksSeen} blocks · fonts ${kb(totalBefore)} -> ${kb(totalAfter)}`,
);
